In [1]:
import pandas as pd
import json

# Read the JSON file into a Python object
with open('/content/drive/MyDrive/MOF/471mofs_030618.json', 'r') as f:
    data = json.load(f)

# Convert the JSON object to a Pandas DataFrame
df = pd.json_normalize(data)
df_transposed = df.transpose()
# Write the DataFrame to an Excel file
df_transposed.to_csv('data.csv', index=False)

In [2]:
C3H6O_rows = df_transposed[df_transposed.index.str.contains('C3H6O_acetone')]
C3H6O_rows.head(5)

                                                                           0
ABUWOJ.C3H6O_acetone.pressure (Pa)     [319253.0, 31925.3, 3192.53, 319.253]
ABUWOJ.C3H6O_acetone.loading (mmol/g)    [3.32229, 3.45412, 3.17716, 2.8947]
ACOLIP.C3H6O_acetone.pressure (Pa)     [319253.0, 31925.3, 3192.53, 319.253]
ACOLIP.C3H6O_acetone.loading (mmol/g)    [2.08344, 2.1188, 2.07101, 1.99508]
AFITIT.C3H6O_acetone.pressure (Pa)     [319253.0, 31925.3, 3192.53, 319.253]

In [3]:
C3H6O_pr=C3H6O_rows[C3H6O_rows.index.str.contains('pressure')]
C3H6O_ad=C3H6O_rows[C3H6O_rows.index.str.contains('loading')]

In [4]:
C3H6O_pr.columns = ['P']
C3H6O_pr.head(5)

                                                                          P
ABUWOJ.C3H6O_acetone.pressure (Pa)    [319253.0, 31925.3, 3192.53, 319.253]
ACOLIP.C3H6O_acetone.pressure (Pa)    [319253.0, 31925.3, 3192.53, 319.253]
AFITIT.C3H6O_acetone.pressure (Pa)    [319253.0, 31925.3, 3192.53, 319.253]
AGARUW.C3H6O_acetone.pressure (Pa)    [319253.0, 31925.3, 3192.53, 319.253]
AHOKIR01.C3H6O_acetone.pressure (Pa)  [319253.0, 31925.3, 3192.53, 319.253]

In [5]:
C3H6O_pr1=C3H6O_pr['P'].astype(str).str.replace('[', '').str.replace(']', '')

C3H6O_pr2 = C3H6O_pr1.to_frame()
C3H6O_pr2.head(5)

<ipython-input-5-a0c7d0d7757a>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  C3H6O_pr1=C3H6O_pr['P'].astype(str).str.replace('[', '').str.replace(']', '')

                                                                        P
ABUWOJ.C3H6O_acetone.pressure (Pa)    319253.0, 31925.3, 3192.53, 319.253
ACOLIP.C3H6O_acetone.pressure (Pa)    319253.0, 31925.3, 3192.53, 319.253
AFITIT.C3H6O_acetone.pressure (Pa)    319253.0, 31925.3, 3192.53, 319.253
AGARUW.C3H6O_acetone.pressure (Pa)    319253.0, 31925.3, 3192.53, 319.253
AHOKIR01.C3H6O_acetone.pressure (Pa)  319253.0, 31925.3, 3192.53, 319.253

In [6]:
C3H6O_pr2[['p1','p2','p3','p4']] = C3H6O_pr1.str.split(',', expand=True)

In [8]:
C3H6O_pr3 = C3H6O_pr2.drop('P', axis=1)
C3H6O_pr3

                                            p1        p2        p3        p4
ABUWOJ.C3H6O_acetone.pressure (Pa)    319253.0   31925.3   3192.53   319.253
ACOLIP.C3H6O_acetone.pressure (Pa)    319253.0   31925.3   3192.53   319.253
AFITIT.C3H6O_acetone.pressure (Pa)    319253.0   31925.3   3192.53   319.253
AGARUW.C3H6O_acetone.pressure (Pa)    319253.0   31925.3   3192.53   319.253
AHOKIR01.C3H6O_acetone.pressure (Pa)  319253.0   31925.3   3192.53   319.253
...                                        ...       ...       ...       ...
ZESFUY.C3H6O_acetone.pressure (Pa)    319253.0   31925.3   3192.53   319.253
ZIBGIC.C3H6O_acetone.pressure (Pa)    319253.0   31925.3   3192.53   319.253
ZIDDIB.C3H6O_acetone.pressure (Pa)    319253.0   31925.3   3192.53   319.253
ZIKJIO.C3H6O_acetone.pressure (Pa)    319253.0   31925.3   3192.53   319.253
ZISYAD.C3H6O_acetone.pressure (Pa)    319253.0   31925.3   3192.53   319.253

[471 rows x 4 columns]

**Summary of pressure part**

In [9]:
# C2H4 pressure 
C3H6O_pr.columns = ['P']
C3H6O_pr1=C3H6O_pr['P'].astype(str).str.replace('[', '').str.replace(']', '')
C3H6O_pr2=C3H6O_pr1.to_frame()
C3H6O_pr2[['p1','p2','p3','p4']] = C3H6O_pr1.str.split(',', expand=True)
C3H6O_pr3 = C3H6O_pr2.drop('P', axis=1)
C3H6O_pr3

<ipython-input-9-77b12d9cd7e5>:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  C3H6O_pr1=C3H6O_pr['P'].astype(str).str.replace('[', '').str.replace(']', '')

                                            p1        p2        p3        p4
ABUWOJ.C3H6O_acetone.pressure (Pa)    319253.0   31925.3   3192.53   319.253
ACOLIP.C3H6O_acetone.pressure (Pa)    319253.0   31925.3   3192.53   319.253
AFITIT.C3H6O_acetone.pressure (Pa)    319253.0   31925.3   3192.53   319.253
AGARUW.C3H6O_acetone.pressure (Pa)    319253.0   31925.3   3192.53   319.253
AHOKIR01.C3H6O_acetone.pressure (Pa)  319253.0   31925.3   3192.53   319.253
...                                        ...       ...       ...       ...
ZESFUY.C3H6O_acetone.pressure (Pa)    319253.0   31925.3   3192.53   319.253
ZIBGIC.C3H6O_acetone.pressure (Pa)    319253.0   31925.3   3192.53   319.253
ZIDDIB.C3H6O_acetone.pressure (Pa)    319253.0   31925.3   3192.53   319.253
ZIKJIO.C3H6O_acetone.pressure (Pa)    319253.0   31925.3   3192.53   319.253
ZISYAD.C3H6O_acetone.pressure (Pa)    319253.0   31925.3   3192.53   319.253

[471 rows x 4 columns]

**Ad**

In [11]:
C3H6O_ad.columns = ['Ad']
C3H6O_ad1=C3H6O_ad['Ad'].astype(str).str.replace('[', '').str.replace(']', '')
C3H6O_ad2=C3H6O_ad1.to_frame()
C3H6O_ad2[['ad1','ad2','ad3','ad4']] = C3H6O_ad1.str.split(',', expand=True)
C3H6O_ad3 = C3H6O_ad2.drop('Ad', axis=1)
C3H6O_ad3

<ipython-input-11-2315dc696d77>:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  C3H6O_ad1=C3H6O_ad['Ad'].astype(str).str.replace('[', '').str.replace(']', '')

,ad1,ad2,ad3,ad4
ABUWOJ.C3H6O_acetone.loading (mmol/g),3.32229,3.45412,3.17716,2.8947
ACOLIP.C3H6O_acetone.loading (mmol/g),2.08344,2.1188,2.07101,1.99508
AFITIT.C3H6O_acetone.loading (mmol/g),3.68864,3.76371,3.52726,3.1285
AGARUW.C3H6O_acetone.loading (mmol/g),1.54803,1.55114,1.54759,1.5437
AHOKIR01.C3H6O_acetone.loading (mmol/g),0.000142495,0.000197457,1.62851e-05,0.0
...,...,...,...,...
ZESFUY.C3H6O_acetone.loading (mmol/g),7.89149,7.86397,7.44732,6.64518
ZIBGIC.C3H6O_acetone.loading (mmol/g),0.0,0.0,0.0,0.0
ZIDDIB.C3H6O_acetone.loading (mmol/g),0.689706,0.689706,0.689706,0.689706
ZIKJIO.C3H6O_acetone.loading (mmol/g),9.55776,9.70313,8.93353,7.33225
ZISYAD.C3H6O_acetone.loading (mmol/g),2.84782,2.89762,2.8259,2.49221

In [12]:
#combine
l1=C3H6O_ad3.values.tolist()
l2=C3H6O_pr3.values.tolist()
for i in range(len(l1)):
    l1[i].extend(l2[i])

C3H6O_new=pd.DataFrame(l1,columns=C3H6O_ad3.columns.tolist()+C3H6O_pr3.columns.tolist())
C3H6O_new.head(5)

,ad1,ad2,ad3,ad4,p1,p2,p3,p4
0,3.32229,3.45412,3.17716,2.8947,319253.0,31925.3,3192.53,319.253
1,2.08344,2.1188,2.07101,1.99508,319253.0,31925.3,3192.53,319.253
2,3.68864,3.76371,3.52726,3.1285,319253.0,31925.3,3192.53,319.253
3,1.54803,1.55114,1.54759,1.5437,319253.0,31925.3,3192.53,319.253
4,0.000142495,0.000197457,1.62851e-05,0.0,319253.0,31925.3,3192.53,319.253

In [13]:
# change column sequence
new_order = ['p1','ad1', 'p2', 'ad2','p2','p3','ad3','p4','ad3']
C3H6O_update = C3H6O_new.reindex(columns=new_order)

C3H6O_update

#C3H6O_update.to_csv('C3H6O.csv', index=False)

In [14]:
C3H6O_in=C3H6O_pr.index
C3H6O_in2=C3H6O_in.str.replace(' ', '').str.replace('Pa', '').str.replace('C2H6', '').str.replace('(', '').str.replace(')', '').str.replace('.', '').str.replace('C3H6O_ethenepressure', '')
print(C3H6O_in2)

Index(['ABUWOJC3H6O_acetonepressure', 'ACOLIPC3H6O_acetonepressure',
       'AFITITC3H6O_acetonepressure', 'AGARUWC3H6O_acetonepressure',
       'AHOKIR01C3H6O_acetonepressure', 'AMIKOXC3H6O_acetonepressure',
       'AMILUEC3H6O_acetonepressure', 'AMIMEPC3H6O_acetonepressure',
       'AMUCOBC3H6O_acetonepressure', 'ANUGIAC3H6O_acetonepressure',
       ...
       'ZARZAVC3H6O_acetonepressure', 'ZEDRADC3H6O_acetonepressure',
       'ZEDRORC3H6O_acetonepressure', 'ZERNANC3H6O_acetonepressure',
       'ZERQOEC3H6O_acetonepressure', 'ZESFUYC3H6O_acetonepressure',
       'ZIBGICC3H6O_acetonepressure', 'ZIDDIBC3H6O_acetonepressure',
       'ZIKJIOC3H6O_acetonepressure', 'ZISYADC3H6O_acetonepressure'],
      dtype='object', length=471)

<ipython-input-14-f700bed041e4>:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  C3H6O_in2=C3H6O_in.str.replace(' ', '').str.replace('Pa', '').str.replace('C2H6', '').str.replace('(', '').str.replace(')', '').str.replace('.', '').str.replace('C3H6O_ethenepressure', '')
<ipython-input-14-f700bed041e4>:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  C3H6O_in2=C3H6O_in.str.replace(' ', '').str.replace('Pa', '').str.replace('C2H6', '').str.replace('(', '').str.replace(')', '').str.replace('.', '').str.replace('C3H6O_ethenepressure', '')
<ipython-input-14-f700bed041e4>:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  C3H6O_in2=C3H6O_in.str.replace(' ', '').str.replace('Pa', '').str.replace('C2H6', '').str.replace('(', '').str.replace(')', '').str.replace('.', '').str.replace('C3H6O_ethenepressure', '')

In [15]:
C3H6O_update.set_index(C3H6O_in2, inplace=True)
C3H6O_update

,p1,ad1,p2,ad2,p2,p3,ad3,p4,ad3
ABUWOJC3H6O_acetonepressure,319253.0,3.32229,31925.3,3.45412,31925.3,3192.53,3.17716,319.253,3.17716
ACOLIPC3H6O_acetonepressure,319253.0,2.08344,31925.3,2.1188,31925.3,3192.53,2.07101,319.253,2.07101
AFITITC3H6O_acetonepressure,319253.0,3.68864,31925.3,3.76371,31925.3,3192.53,3.52726,319.253,3.52726
AGARUWC3H6O_acetonepressure,319253.0,1.54803,31925.3,1.55114,31925.3,3192.53,1.54759,319.253,1.54759
AHOKIR01C3H6O_acetonepressure,319253.0,0.000142495,31925.3,0.000197457,31925.3,3192.53,1.62851e-05,319.253,1.62851e-05
...,...,...,...,...,...,...,...,...,...
ZESFUYC3H6O_acetonepressure,319253.0,7.89149,31925.3,7.86397,31925.3,3192.53,7.44732,319.253,7.44732
ZIBGICC3H6O_acetonepressure,319253.0,0.0,31925.3,0.0,31925.3,3192.53,0.0,319.253,0.0
ZIDDIBC3H6O_acetonepressure,319253.0,0.689706,31925.3,0.689706,31925.3,3192.53,0.689706,319.253,0.689706
ZIKJIOC3H6O_acetonepressure,319253.0,9.55776,31925.3,9.70313,31925.3,3192.53,8.93353,319.253,8.93353
ZISYADC3H6O_acetonepressure,319253.0,2.84782,31925.3,2.89762,31925.3,3192.53,2.8259,319.253,2.8259

In [16]:
C3H6O_update.to_csv('C3H6O.csv', index=True)